server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chysoftoa?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Huawei@123

    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

mvc:
  view:
    prefix: /
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    cn.zgx.tatistician.dao : debug

time:
  corn: 56




